### ISSUE TITLE
junrar legal issues

### ISSUE THREAD

**Issue by michaeldav** [edmund-wagner/junrar#8]
Hello Edmund,

My name is Michael and I am with IBM software labs.

We would like to use JUNRAR library in one of our projects.

Can you be so kind to shed some light on few legal issues with the library?

What exactly the license terms actually apply to the library, this https://github.com/edmund-wagner/junrar/blob/master/license.txt license talks about UNRAR which seems a different software entity?
Are Junrar and Unrar related in any way? Are their licenses related?
We notice on the SourceForge that the project was removed allegedly for some sort of violation? Can you please comment on this?

Thanks a lot!

Michael Davidovich

Content Discovery Group.

**Comment by edmund-wagner** [comment]
Hello Michael,

junrar is a java port of unrar with some additional wrapper code so the unrar license applys to most of the code.
the license itself is pretty open, you are not allowed to "... code may not be used to develop a RAR (WinRAR) compatible archiver" and to keep that information in the source.

Junrar was removed from sf because they only want to support osi compliant oss licenses. Unfortunatelly a lot of contributions in form of svn history, forums, etc.. was lost when they removed it.

Hope this helps.

Kind Regards,
Edmund Wagner

**Comment by michaeldav** [comment]
Thanks a lot for the clarification.

Michael
